version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV:development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=steven
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=mYsEcret
    command: npm run dev

  percona-mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=steven
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

  percona-mysql-db:
    environment:
      MYSQL_ROOT_PASSWORD: beta/svp*.Mysql123
      MYSQL_DATABASE: foodly
    ports:
      - "4406:3306"

  nginx:
    ports:
      - "3000:80"
